# SOPS configuration for nix secrets
# Keys that can decrypt secrets
keys:
  - &emmanuel age18yjmpzzy0xg2r67epfvtkzjs9pql7cuhwadl6c0559vme6ny5e7qah7gkr
  - &pearltrees age1lrw6uvplt8salzrq5nl6fskw2cavcac4vg5dzksrxswxvy7j3yqsdmlxss

# Rules for encrypting secrets files
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *emmanuel
          - *pearltrees
